# Generated by Django 3.1.1 on 2020-09-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'diaries'},
        ),
        migrations.AddField(
            model_name='diary',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
