# Generated by Django 3.1.1 on 2020-09-06 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0002_auto_20200906_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='user',
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
