# Generated by Django 3.1.1 on 2020-09-06 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0003_auto_20200906_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='user',
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
